In [1]:
import pandas as pd
import numpy as np

In [2]:
# read file lunar_births.csv in a data frame
df = pd.read_csv('lunar_births.csv')
df.head()

       Lunar phase  # days  # births
0         New moon      24      7680
1  Waxing crescent     152     48442
2    First quarter      24      7579
3   Waxing gibbous     149     47814
4        Full moon      24      7711

In [7]:
# add expected_births column to the data frame
tot_births = df['# births'].sum()
tot_days = df['# days'].sum()
print(tot_births)
print(tot_days)

df['fraction_days'] = round(df['# days'] / tot_days,4)
df['expected_births'] = round(df['fraction_days'] * tot_births,2)
df

222784
699

       Lunar phase  # days  # births  fraction_days  expected_births
0         New moon      24      7680         0.0343          7641.49
1  Waxing crescent     152     48442         0.2175         48455.52
2    First quarter      24      7579         0.0343          7641.49
3   Waxing gibbous     149     47814         0.2132         47497.55
4        Full moon      24      7711         0.0343          7641.49
5   Waning gibbous     150     47595         0.2146         47809.45
6     Last quarter      24      7733         0.0343          7641.49
7  Waning crescent     152     48230         0.2175         48455.52

In [20]:
df['x2_contrib'] = (df['# births'] - df['expected_births'])**2 / df['expected_births']
x2_contrib_sum = df['x2_contrib'].sum()
print(f"Sum of contributions to chi-square statistic: {x2_contrib_sum:.4f}")

# compute the p-value associated to the chi-square x2_contrib_sum ussing cdf of chi-square distribution with 7 degrees of freedom
from scipy.stats import chi2
p_value = 1 - chi2.cdf(x2_contrib_sum, df=7)
print(f"p-value: {p_value:.4f}")

Sum of contributions to chi-square statistic: 6.5569
p-value: 0.4764

In [15]:
alpha = 0.05
# compute cirtical value for chi-square distribution with 7 degrees of freedom
from scipy.stats import chi2
critical_value = chi2.ppf(1-alpha, df=7) # 1-alhpa, I look for large chaange
print(f"Critical value: {critical_value:.4f}")

if x2_contrib_sum > critical_value:
    print("Reject the null hypothesis: there is a significant difference between observed and expected births.")
else:
    print("Fail to reject the null hypothesis: there is no significant difference between observed and expected births.")

Critical value: 14.0671
Fail to reject the null hypothesis: there is no significant difference between observed and expected births.

In [16]:
# compute chi-square statistic and p-value
from scipy.stats import chisquare

chi2_stat, p_value = chisquare(f_obs=df['# births'], f_exp=df['expected_births'])
print(f"Chi-square statistic: {chi2_stat:.4f}")
print(f"p-value: {p_value:.4f}")

Chi-square statistic: 6.5569
p-value: 0.4764